services:
  tch2-full-node:
    image: ghcr.io/tempoxyz/tempo:latest
    restart: unless-stopped
#    network_mode: host
    volumes:
      - ./config:/config
      - ./data:/data
    command: >
      node
      --chain /config/genesis.json
      --datadir /data/full-node
      --trusted-peers enode://7ac7a70e0633614868bbe65904b4172c7b967bc34ce6f487247d4873dec8fda35643a7ed1cdac522b9cd8f147d003968aa708dd631a41fe3562d5b9e6feb101f@135.181.193.101:3001
      --follow ws://135.181.193.101:8546
      --port 3001
      --discovery.port 3001
      --p2p-secret-key /config/enode.key
      --authrpc.port 3003
      --ws
      --ws.port 8546
      --ws.addr 0.0.0.0
      --ws.api all
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api all
    ports:
      - "3000:3000"  # Consensus P2P
      - "3001:3001"  # Execution P2P
      - "3002:3002"  # Metrics
      - "3003:3003"  # AuthRPC
      - "8545:8545"  # HTTP RPC
      - "8546:8546"  # HTTP RPC
      
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

